/* Fixture data for the prototype. PT-BR strings. */

const VAGA = {
  id: "vag_8821",
  title: "Engenheiro(a) de Software Sênior",
  squad: "Plataforma · Time Núcleo",
  company: "Moove Cars",
  companyShort: "MC",
  level: "Sênior",
  workModel: "Híbrido",
  city: "São Paulo, SP",
  salaryMin: 18000,
  salaryMax: 26000,
  contract: "CLT",
  posted: "há 6 dias",
  hardSkills: ["Python", "Postgres", "AWS", "Docker", "TypeScript"],
  softSkills: ["Autonomia", "Comunicação", "Mentoria"],
  ocean: { O: 0.78, C: 0.85, E: 0.55, A: 0.62, N: 0.30 },
  oceanWeights: { O: 1.0, C: 1.2, E: 0.8, A: 0.9, N: 1.1 },
  // ranges of acceptable spread per dimension (for the band on the bar chart)
  oceanBand: 0.18,
  stats: {
    candidates: 87,
    bilateral: 12,
    interviewed: 4,
    avgMatch: 71,
  },
  description:
    "Procuramos engenheiro(a) sênior para liderar a evolução da plataforma de matching. Trabalhamos com Python, Postgres + pgvector, FastAPI e infra em AWS. Cultura de autonomia, decisões com dados e mentoria entre pares.",
};

const CANDIDATES = [
  {
    id: "c_001",
    name: "Beatriz Almeida",
    initials: "BA",
    headline: "Engenheira de Plataforma · 7 anos",
    location: "São Paulo, SP",
    available: "Disponível em 30 dias",
    photoColor: ["#8B5CF6", "#3AB0FF"],
    skills: ["Python", "Postgres", "AWS", "Docker", "Kafka"],
    score: 0.94,
    bilateral: true,
    status: "interview",
    ocean:        { O: 0.82, C: 0.88, E: 0.50, A: 0.66, N: 0.28 },
    oceanFacets:  { O: ["Curiosidade alta", "Criatividade aplicada"], C: ["Disciplina", "Responsabilidade"], E: ["Equilibrada"], A: ["Cooperativa"], N: ["Estável"] },
    salary: 22000,
    workModel: "Híbrido",
    languages: [["Português","Nativo"],["Inglês","Avançado"],["Espanhol","Intermediário"]],
    education: { level: "Mestrado", course: "Ciência da Computação", institution: "USP" },
    timeline: [
      { when: "26 abr · 14:32", what: "Aplicação enviada via match recíproco", done: true },
      { when: "27 abr · 09:10", what: "Triagem aprovada por Lucas F.", done: true },
      { when: "30 abr · 11:00", what: "Entrevista técnica agendada", done: false },
    ],
    summary:
      "Forte alinhamento com a cultura de autonomia. Histórico de liderança técnica em squads de plataforma. Match recíproco — também priorizou a vaga.",
  },
  {
    id: "c_002",
    name: "Caio Mendes",
    initials: "CM",
    headline: "Backend Sênior · 9 anos",
    location: "Curitiba, PR · Remoto",
    available: "Imediato",
    photoColor: ["#3AB0FF", "#10B981"],
    skills: ["Python", "FastAPI", "Postgres", "GCP", "Redis"],
    score: 0.89,
    bilateral: true,
    status: "contacted",
    ocean:       { O: 0.74, C: 0.82, E: 0.45, A: 0.70, N: 0.32 },
    salary: 24000,
    workModel: "Remoto",
    languages: [["Português","Nativo"],["Inglês","Fluente"]],
    education: { level: "Graduação", course: "Engenharia da Computação", institution: "UFPR" },
    timeline: [
      { when: "25 abr · 18:04", what: "Aplicação enviada", done: true },
      { when: "28 abr · 10:22", what: "Mensagem inicial enviada", done: true },
    ],
    summary: "Perfil mais introspectivo, alta consciência. Pode pesar contra ritmo de cerimônias do squad.",
  },
  {
    id: "c_003",
    name: "Renata Vieira",
    initials: "RV",
    headline: "Tech Lead · 11 anos",
    location: "Rio de Janeiro, RJ",
    available: "Disponível em 60 dias",
    photoColor: ["#F59E0B", "#EF4444"],
    skills: ["Python", "AWS", "Terraform", "TypeScript", "K8s"],
    score: 0.86,
    bilateral: false,
    status: "new",
    ocean:       { O: 0.84, C: 0.78, E: 0.72, A: 0.55, N: 0.34 },
    salary: 26000,
    workModel: "Híbrido",
    languages: [["Português","Nativo"],["Inglês","Avançado"]],
    education: { level: "Pós-graduação", course: "Arquitetura de Software", institution: "PUC-Rio" },
    timeline: [
      { when: "24 abr · 09:48", what: "Match unilateral gerado", done: true },
    ],
    summary: "Comunicadora forte, mais expansiva que a média do time. Pode acelerar onboarding mas exige espaço.",
  },
  {
    id: "c_004",
    name: "Daniel Souza",
    initials: "DS",
    headline: "Engenheiro de Software · 6 anos",
    location: "Belo Horizonte, MG",
    available: "Disponível em 45 dias",
    photoColor: ["#3AB0FF", "#8B5CF6"],
    skills: ["TypeScript", "Node", "Postgres", "AWS"],
    score: 0.79,
    bilateral: false,
    status: "new",
    ocean:       { O: 0.69, C: 0.82, E: 0.58, A: 0.68, N: 0.36 },
    salary: 18500,
    workModel: "Remoto",
    languages: [["Português","Nativo"],["Inglês","Avançado"]],
    education: { level: "Graduação", course: "Sistemas de Informação", institution: "UFMG" },
    timeline: [{ when: "23 abr · 16:11", what: "Match unilateral gerado", done: true }],
    summary: "Sólido em backend, ainda construindo profundidade em infra. Boa cultura de cooperação.",
  },
  {
    id: "c_005",
    name: "Mariana Cabral",
    initials: "MC",
    headline: "Engenheira ML · 5 anos",
    location: "Florianópolis, SC",
    available: "Imediato",
    photoColor: ["#10B981", "#3AB0FF"],
    skills: ["Python", "PyTorch", "AWS", "Postgres"],
    score: 0.76,
    bilateral: false,
    status: "new",
    ocean:       { O: 0.91, C: 0.74, E: 0.60, A: 0.58, N: 0.41 },
    salary: 20000,
    workModel: "Híbrido",
    languages: [["Português","Nativo"],["Inglês","Avançado"],["Francês","Básico"]],
    education: { level: "Mestrado", course: "Inteligência Artificial", institution: "UFSC" },
    timeline: [{ when: "22 abr · 11:50", what: "Match unilateral gerado", done: true }],
    summary: "Abertura altíssima. Pode trazer ideias novas mas pede consistência de execução.",
  },
  {
    id: "c_006",
    name: "Felipe Tanaka",
    initials: "FT",
    headline: "Senior SRE · 8 anos",
    location: "São Paulo, SP",
    available: "Disponível em 30 dias",
    photoColor: ["#1a8fdb", "#8B5CF6"],
    skills: ["AWS", "K8s", "Terraform", "Python"],
    score: 0.74,
    bilateral: false,
    status: "advanced",
    ocean:       { O: 0.66, C: 0.92, E: 0.40, A: 0.64, N: 0.26 },
    salary: 23000,
    workModel: "Presencial",
    languages: [["Português","Nativo"],["Inglês","Avançado"]],
    education: { level: "Graduação", course: "Engenharia da Computação", institution: "Mauá" },
    timeline: [
      { when: "20 abr · 09:13", what: "Aplicação enviada", done: true },
      { when: "21 abr · 14:44", what: "Triagem aprovada", done: true },
      { when: "23 abr · 16:00", what: "Entrevista técnica concluída", done: true },
      { when: "26 abr · 10:00", what: "Aprovado pelo time técnico", done: true },
    ],
    summary: "Perfil de execução máxima, baixa neuroticismo. Pode reforçar disciplina de SRE.",
  },
  {
    id: "c_007",
    name: "Júlia Pacheco",
    initials: "JP",
    headline: "Backend Pleno+ · 5 anos",
    location: "Recife, PE",
    available: "Disponível em 30 dias",
    photoColor: ["#8B5CF6", "#F59E0B"],
    skills: ["Python", "Django", "Postgres"],
    score: 0.71,
    bilateral: false,
    status: "contacted",
    ocean:       { O: 0.72, C: 0.81, E: 0.62, A: 0.74, N: 0.40 },
    salary: 17500,
    workModel: "Remoto",
    languages: [["Português","Nativo"],["Inglês","Intermediário"]],
    education: { level: "Graduação", course: "Ciência da Computação", institution: "UFPE" },
    timeline: [{ when: "19 abr · 12:11", what: "Aplicação enviada", done: true }],
    summary: "Personalidade muito agradável. Pode ser ponte natural com o produto.",
  },
  {
    id: "c_008",
    name: "André Lopes",
    initials: "AL",
    headline: "Fullstack · 4 anos",
    location: "Porto Alegre, RS",
    available: "Imediato",
    photoColor: ["#EF4444", "#3AB0FF"],
    skills: ["TypeScript", "Node", "React"],
    score: 0.62,
    bilateral: false,
    status: "declined",
    ocean:       { O: 0.55, C: 0.66, E: 0.78, A: 0.50, N: 0.50 },
    salary: 14000,
    workModel: "Remoto",
    languages: [["Português","Nativo"],["Inglês","Intermediário"]],
    education: { level: "Graduação", course: "Análise de Sistemas", institution: "PUCRS" },
    timeline: [
      { when: "18 abr · 10:00", what: "Aplicação enviada", done: true },
      { when: "21 abr · 18:00", what: "Recusado por nível", done: true },
    ],
    summary: "Energia extrovertida, ainda júnior para o nível da vaga.",
  },
];

const STATUS_LABELS = {
  new: "Novo",
  contacted: "Contatado",
  interview: "Em entrevista",
  advanced: "Avançado",
  declined: "Recusado",
};

const OCEAN_KEYS = ["O","C","E","A","N"];
const OCEAN_LONG = {
  O: "Abertura",
  C: "Conscienciosidade",
  E: "Extroversão",
  A: "Amabilidade",
  N: "Neuroticismo",
};
const OCEAN_DESCRIPTIONS = {
  O: "Curiosidade, criatividade, abertura ao novo",
  C: "Organização, disciplina, foco",
  E: "Sociabilidade, energia em grupo",
  A: "Cooperação, empatia",
  N: "Reatividade emocional (menor é mais estável)",
};
const OCEAN_COLORS = {
  O: "#8B5CF6",
  C: "#3B82F6",
  E: "#F59E0B",
  A: "#10B981",
  N: "#EF4444",
};

Object.assign(window, {
  VAGA, CANDIDATES, STATUS_LABELS, OCEAN_KEYS, OCEAN_LONG, OCEAN_DESCRIPTIONS, OCEAN_COLORS,
});
